import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { getParticipantsWithConsensus } from '@/lib/db';
import { saveConsensusOverride, recalculateConsensus } from '@/app/consensus/actions';
export default async function ConsensusPage() {
    const participants = await getParticipantsWithConsensus();
    return (_jsx("div", { className: "min-h-screen bg-gray-50 p-6", children: _jsxs("div", { className: "mx-auto max-w-7xl", children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900 mb-6", children: "Participant Consensus" }), _jsx("div", { className: "mb-4", children: _jsx("form", { action: recalculateConsensus, className: "flex items-center space-x-3", children: _jsx("button", { type: "submit", className: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded", children: "Recalculate Consensus from Evaluations" }) }) }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-full divide-y divide-gray-200", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { scope: "col", className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Photo" }), _jsx("th", { scope: "col", className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Name" }), _jsx("th", { scope: "col", className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Consensus Level" }), _jsx("th", { scope: "col", className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Average Ranking" }), _jsx("th", { scope: "col", className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Actions" })] }) }), _jsx("tbody", { className: "bg-white divide-y divide-gray-200", children: participants.map((participant) => {
                                    var _a, _b;
                                    return (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: participant.photoUrl ? (_jsx("img", { src: participant.photoUrl, alt: participant.name, className: "h-10 w-10 rounded-full object-cover" })) : (_jsx("div", { className: "h-10 w-10 rounded-full bg-gray-300 flex items-center justify-center", children: _jsx("span", { className: "text-xs text-gray-600", children: "No Photo" }) })) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900", children: participant.name }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsxs("form", { action: saveConsensusOverride, className: "flex space-x-2", method: "POST", children: [_jsx("input", { type: "hidden", name: "participantId", value: participant.id }), _jsx("input", { type: "text", name: "consensusLevel", value: (_a = participant.consensusLevel) !== null && _a !== void 0 ? _a : '', className: "border border-gray-300 rounded-md px-2 py-1 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500", placeholder: "Enter level" }), _jsx("button", { type: "submit", className: "bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-3 rounded", children: "Save" })] }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsxs("form", { action: saveConsensusOverride, className: "flex space-x-2", method: "POST", children: [_jsx("input", { type: "hidden", name: "participantId", value: participant.id }), _jsx("input", { type: "number", name: "averageRanking", value: (_b = participant.averageRanking) !== null && _b !== void 0 ? _b : '', step: "0.1", className: "border border-gray-300 rounded-md px-2 py-1 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500", placeholder: "Enter ranking" }), _jsx("button", { type: "submit", className: "bg-green-500 hover:bg-green-700 text-white font-bold py-1 px-3 rounded", children: "Save" })] }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm font-medium", children: _jsxs("p", { className: "text-gray-500", children: ["Last updated: ", participant.updatedAt ? new Date(participant.updatedAt).toLocaleString() : 'Never'] }) })] }, participant.id));
                                }) })] }) })] }) }));
}
